"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Ostia engine contract, major version 1 (spec section 14, ADR-03).

Every message is sent on the worker's standard input or output as one frame: a 4-byte big-endian length,
then the encoded message. The analysed object is never in a message: it is passed read-only as file
descriptor 3. Within major version 1, changes are additive only (new fields, new enum values); field
numbers and types never change (CTR-04, checked against compat.json).
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Origin:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _OriginEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Origin.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ORIGIN_UNSPECIFIED: _Origin.ValueType  # 0
    """Not set: refused."""
    FILE: _Origin.ValueType  # 1
    """A file of the medium's file system."""
    EXTRACTED: _Origin.ValueType  # 2
    """An object extracted from a container (archive, document, installer)."""
    ALT_STREAM: _Origin.ValueType  # 3
    """An alternate data stream."""
    CARVED: _Origin.ValueType  # 4
    """An object carved from unallocated or slack space."""
    BOOT_CODE: _Origin.ValueType  # 5
    """Boot code (MBR, VBR, EFI system partition)."""

class Origin(_Origin, metaclass=_OriginEnumTypeWrapper):
    """Where an object comes from."""

ORIGIN_UNSPECIFIED: Origin.ValueType  # 0
"""Not set: refused."""
FILE: Origin.ValueType  # 1
"""A file of the medium's file system."""
EXTRACTED: Origin.ValueType  # 2
"""An object extracted from a container (archive, document, installer)."""
ALT_STREAM: Origin.ValueType  # 3
"""An alternate data stream."""
CARVED: Origin.ValueType  # 4
"""An object carved from unallocated or slack space."""
BOOT_CODE: Origin.ValueType  # 5
"""Boot code (MBR, VBR, EFI system partition)."""
Global___Origin: _TypeAlias = Origin  # noqa: Y015

class _Status:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Status.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    STATUS_UNSPECIFIED: _Status.ValueType  # 0
    """Not set: refused."""
    OK: _Status.ValueType  # 1
    """The engine analysed the object."""
    ERROR: _Status.ValueType  # 2
    """The engine failed."""
    TIMEOUT: _Status.ValueType  # 3
    """The engine ran out of time."""
    UNSUPPORTED: _Status.ValueType  # 4
    """The engine does not handle this type of object."""

class Status(_Status, metaclass=_StatusEnumTypeWrapper):
    """Outcome of an engine run."""

STATUS_UNSPECIFIED: Status.ValueType  # 0
"""Not set: refused."""
OK: Status.ValueType  # 1
"""The engine analysed the object."""
ERROR: Status.ValueType  # 2
"""The engine failed."""
TIMEOUT: Status.ValueType  # 3
"""The engine ran out of time."""
UNSUPPORTED: Status.ValueType  # 4
"""The engine does not handle this type of object."""
Global___Status: _TypeAlias = Status  # noqa: Y015

class _Hint:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _HintEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Hint.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    HINT_UNSPECIFIED: _Hint.ValueType  # 0
    """Not set."""
    NONE: _Hint.ValueType  # 1
    """No opinion."""
    CLEAN: _Hint.ValueType  # 2
    """Nothing found."""
    SUSPICIOUS: _Hint.ValueType  # 3
    """Something suspicious was found."""
    MALICIOUS: _Hint.ValueType  # 4
    """Something malicious was found."""

class Hint(_Hint, metaclass=_HintEnumTypeWrapper):
    """The engine's opinion; verdicts are decided by the policy, never by an engine."""

HINT_UNSPECIFIED: Hint.ValueType  # 0
"""Not set."""
NONE: Hint.ValueType  # 1
"""No opinion."""
CLEAN: Hint.ValueType  # 2
"""Nothing found."""
SUSPICIOUS: Hint.ValueType  # 3
"""Something suspicious was found."""
MALICIOUS: Hint.ValueType  # 4
"""Something malicious was found."""
Global___Hint: _TypeAlias = Hint  # noqa: Y015

@_typing.final
class ContractVersion(_message.Message):
    """Version of the contract a message was written against. A decoder refuses any major other than its
    own (a missing version reads as major 0); a newer minor is accepted.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MAJOR_FIELD_NUMBER: _builtins.int
    MINOR_FIELD_NUMBER: _builtins.int
    major: _builtins.int
    """Major version: 1 for this package."""
    minor: _builtins.int
    """Minor version: additive changes within the major."""
    def __init__(
        self,
        *,
        major: _builtins.int = ...,
        minor: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["major", b"major", "minor", b"minor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ContractVersion: _TypeAlias = ContractVersion  # noqa: Y015

@_typing.final
class Limits(_message.Message):
    """Resource limits the engine runs under."""

    DESCRIPTOR: _descriptor.Descriptor

    MEMORY_BYTES_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    WRITE_BYTES_FIELD_NUMBER: _builtins.int
    memory_bytes: _builtins.int
    """Memory limit in bytes."""
    duration_ms: _builtins.int
    """Wall-clock limit in milliseconds."""
    write_bytes: _builtins.int
    """Limit on bytes the engine may write to its private scratch space."""
    def __init__(
        self,
        *,
        memory_bytes: _builtins.int = ...,
        duration_ms: _builtins.int = ...,
        write_bytes: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_ms", b"duration_ms", "memory_bytes", b"memory_bytes", "write_bytes", b"write_bytes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Limits: _TypeAlias = Limits  # noqa: Y015

@_typing.final
class AnalyzeRequest(_message.Message):
    """Request to analyse one object; the object itself is file descriptor 3, read-only."""

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    OBJECT_ID_FIELD_NUMBER: _builtins.int
    SHA256_FIELD_NUMBER: _builtins.int
    DETECTED_TYPE_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    ORIGIN_FIELD_NUMBER: _builtins.int
    LIMITS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    """Session the object belongs to."""
    object_id: _builtins.str
    """Object identifier within the session."""
    sha256: _builtins.bytes
    """SHA-256 of the object (32 bytes)."""
    detected_type: _builtins.str
    """Type identified from the content, never from the name."""
    size: _builtins.int
    """Size of the object in bytes."""
    origin: Global___Origin.ValueType
    """Where the object comes from."""
    @_builtins.property
    def limits(self) -> Global___Limits:
        """Limits the engine runs under."""

    @_builtins.property
    def version(self) -> Global___ContractVersion:
        """Contract version of this message."""

    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        object_id: _builtins.str = ...,
        sha256: _builtins.bytes = ...,
        detected_type: _builtins.str = ...,
        size: _builtins.int = ...,
        origin: Global___Origin.ValueType = ...,
        limits: Global___Limits | None = ...,
        version: Global___ContractVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["limits", b"limits", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detected_type", b"detected_type", "limits", b"limits", "object_id", b"object_id", "origin", b"origin", "session_id", b"session_id", "sha256", b"sha256", "size", b"size", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AnalyzeRequest: _TypeAlias = AnalyzeRequest  # noqa: Y015

@_typing.final
class Finding(_message.Message):
    """One thing an engine found."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    EVIDENCE_FIELD_NUMBER: _builtins.int
    ATTACK_IDS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Rule, signature or model feature identifier."""
    title: _builtins.str
    """Short human-readable title."""
    severity: _builtins.int
    """Severity from 0 (information) to 4 (critical)."""
    evidence: _builtins.str
    """Metadata supporting the finding (offsets, names, scores), never file content."""
    @_builtins.property
    def attack_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """MITRE ATT&CK technique identifiers."""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        title: _builtins.str = ...,
        severity: _builtins.int = ...,
        evidence: _builtins.str = ...,
        attack_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attack_ids", b"attack_ids", "evidence", b"evidence", "id", b"id", "severity", b"severity", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Finding: _TypeAlias = Finding  # noqa: Y015

@_typing.final
class AnalyzeResponse(_message.Message):
    """Result of analysing one object (CTR-03: engine identity and content version are required)."""

    DESCRIPTOR: _descriptor.Descriptor

    ENGINE_ID_FIELD_NUMBER: _builtins.int
    ENGINE_VERSION_FIELD_NUMBER: _builtins.int
    CONTENT_VERSION_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    HINT_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    FINDINGS_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    engine_id: _builtins.str
    """Engine identifier."""
    engine_version: _builtins.str
    """Engine version."""
    content_version: _builtins.str
    """Version of the rules, signatures or model the engine used."""
    status: Global___Status.ValueType
    """Outcome of the run."""
    hint: Global___Hint.ValueType
    """The engine's opinion."""
    score: _builtins.float
    """Score in [0, 1] for scoring engines."""
    duration_ms: _builtins.int
    """Time the analysis took, in milliseconds."""
    @_builtins.property
    def findings(self) -> _containers.RepeatedCompositeFieldContainer[Global___Finding]:
        """What the engine found."""

    @_builtins.property
    def version(self) -> Global___ContractVersion:
        """Contract version of this message."""

    def __init__(
        self,
        *,
        engine_id: _builtins.str = ...,
        engine_version: _builtins.str = ...,
        content_version: _builtins.str = ...,
        status: Global___Status.ValueType = ...,
        hint: Global___Hint.ValueType = ...,
        score: _builtins.float | None = ...,
        findings: _abc.Iterable[Global___Finding] | None = ...,
        duration_ms: _builtins.int = ...,
        version: Global___ContractVersion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_score", b"_score", "score", b"score", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_score", b"_score", "content_version", b"content_version", "duration_ms", b"duration_ms", "engine_id", b"engine_id", "engine_version", b"engine_version", "findings", b"findings", "hint", b"hint", "score", b"score", "status", b"status", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__score: _TypeAlias = _typing.Literal["score"]  # noqa: Y015
    _WhichOneofArgType__score: _TypeAlias = _typing.Literal["_score", b"_score"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__score) -> _WhichOneofReturnType__score | None: ...

Global___AnalyzeResponse: _TypeAlias = AnalyzeResponse  # noqa: Y015
