#!/usr/bin/env python3
"""SessionStart hook: prints the current state of the rails as context for Claude.

Runs at startup, resume, /clear and after compaction, so the rules and the current
work package survive a context reset. Never fails the session.
"""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path


def sh(args: list[str], root: Path) -> str:
    try:
        return subprocess.run(args, cwd=root, capture_output=True, text=True, timeout=10).stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        return ""


def main() -> None:
    root = Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())
    lines = ["## Ostia rails — session context (generated by .claude/hooks/session_start.py)"]

    branch = sh(["git", "rev-parse", "--abbrev-ref", "HEAD"], root) or "(no git repository yet)"
    m = re.match(r"wp/(\d+\.\d+)-", branch)
    lines.append(f"- Branch: `{branch}`" + (f" → active work package WP-{m.group(1)}" if m else ""))
    if m:
        notes = root / ".wp-notes" / f"WP-{m.group(1)}.md"
        if notes.exists():
            text = notes.read_text(encoding="utf-8")
            st = re.search(r"^## Status\s*\n(.*?)(?=^## |\Z)", text, re.M | re.S)
            lines.append(f"- Working notes: `{notes.relative_to(root)}` — re-read them before acting.")
            if st and st.group(1).strip():
                lines.append("  Last status: " + " / ".join(x.strip() for x in st.group(1).strip().splitlines()[-4:]))
        else:
            lines.append(
                f"- No working notes for WP-{m.group(1)} yet: "
                f"run /wp-start WP-{m.group(1)} if the package was not started."
            )
    if branch in ("main", "master"):
        lines.append("- You are on the default branch: run /wp-start <WP-id> before changing code.")

    status = root / "docs" / "phase-status.md"
    if status.exists():
        text = status.read_text(encoding="utf-8")
        cur = re.search(r"^Current phase:\s*(.+)$", text, re.M)
        if cur:
            lines.append(f"- Current phase: {cur.group(1).strip()}")
        phase = re.search(r"P\d", cur.group(1)) if cur else None
        if phase:
            sec = re.search(rf"^## {phase.group(0)}\b.*?(?=^## |\Z)", text, re.M | re.S)
            if sec:
                todo = re.findall(r"^- \[ \] (WP-\d+\.\d+)", sec.group(0), re.M)
                done = re.findall(r"^- \[x\] (WP-\d+\.\d+)", sec.group(0), re.M | re.I)
                lines.append(
                    f"- {phase.group(0)} work packages: {len(done)} merged, {len(todo)} open"
                    + (f"; next candidates: {', '.join(todo[:4])}" if todo else "")
                )

    locks = sh([os.environ.get("PYTHON", "python3"), "tools/lock/ostia_lock.py", "status"], root)
    if locks:
        lines.append("- Acceptance test locks:\n" + "\n".join(f"    {x}" for x in locks.splitlines()))

    rails = sh([os.environ.get("PYTHON", "python3"), "tools/lock/ostia_lock.py", "rails-verify"], root)
    if "VIOLATION" in rails:
        lines.append(
            "- WARNING: rails files differ from the owner's manifest. Do not continue; tell the owner:\n"
            + "\n".join(f"    {x}" for x in rails.splitlines() if "VIOLATION" in x)
        )

    dirty = sh(["git", "status", "--porcelain"], root)
    if dirty:
        lines.append(f"- Uncommitted changes: {len(dirty.splitlines())} path(s). Check them before starting new work.")

    lines += [
        "",
        "Reminders (full rules in AGENTS.md):",
        "1. One WP per branch. Read it with `python3 tools/kit/req.py WP-x.y` before writing anything.",
        "2. Tests first, tagged with requirement ids; show them failing for the expected reason;",
        "   commit test(...) then feat(...).",
        "3. Never edit, skip, xfail or weaken a test; never touch locked tests/acceptance/** or the rails files.",
        "4. Ambiguity, missing requirement, failing locked test you believe is wrong: stop and ask the owner.",
        "5. `just check` green before saying done. No real malware, secrets, API keys or network calls in tests.",
    ]
    print("\n".join(lines))


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # never break the session
        print(f"(session_start hook error: {exc!r})")
