"""Generated Python code for the ostia.engine.v1 contract (tools/contracts/gen_python.py, ADR-15).

The generated `engine_pb2.py` and `engine_pb2.pyi` are committed under workers-py/common; the script
regenerates them with the protoc bundled in grpcio-tools, and `--check` fails when the committed copy no
longer matches proto/ostia/engine/v1/engine.proto.
"""

import shutil
import sys
import tomllib
from pathlib import Path

import pytest

from tooling_support import REPO, run

GEN = str(REPO / "tools" / "contracts" / "gen_python.py")
GENERATED = REPO / "workers-py" / "common" / "src" / "ostia_common" / "engine_v1"
FILES = ("engine_pb2.py", "engine_pb2.pyi")


def gen(*args: str) -> tuple[int, str]:
    result = run([sys.executable, GEN, *args], cwd=REPO)
    return result.returncode, result.stdout + result.stderr


@pytest.mark.req("TOOLING")
def test_committed_code_matches_the_proto() -> None:
    code, output = gen("--check")
    assert code == 0, output
    assert "generated Python code is up to date" in output


@pytest.mark.req("TOOLING")
def test_generation_writes_the_module_and_its_stub(tmp_path: Path) -> None:
    code, output = gen("--out", str(tmp_path))
    assert code == 0, output
    assert sorted(p.name for p in tmp_path.iterdir()) == ["engine_pb2.py", "engine_pb2.pyi"]
    module = (tmp_path / "engine_pb2.py").read_text()
    header = "# -*- coding: utf-8 -*-\n# Generated by the protocol buffer compiler."
    assert module.startswith(header)
    assert "ostia/engine/v1/engine.proto" in module
    assert "class AnalyzeResponse(_message.Message):" in (tmp_path / "engine_pb2.pyi").read_text()


@pytest.mark.req("TOOLING")
@pytest.mark.parametrize(
    ("change", "message"),
    [
        ("edit module", "engine_pb2.py is out of date: run `just proto`"),
        ("delete stub", "engine_pb2.pyi is missing: run `just proto`"),
    ],
)
def test_check_detects_a_stale_copy(tmp_path: Path, change: str, message: str) -> None:
    copy = tmp_path / "engine_v1"
    copy.mkdir()
    for name in FILES:
        assert (GENERATED / name).is_file(), f"{name} is not committed"
        shutil.copyfile(GENERATED / name, copy / name)
    if change == "edit module":
        (copy / "engine_pb2.py").write_text((copy / "engine_pb2.py").read_text() + "# edited\n")
    else:
        (copy / "engine_pb2.pyi").unlink()
    code, output = gen("--check", "--out", str(copy))
    assert code == 1
    assert message in output


@pytest.mark.req("TOOLING")
def test_ruff_excludes_exactly_the_generated_files() -> None:
    # Q-19: protoc output is not ruff-clean; mypy still checks it through the stub.
    with (REPO / "pyproject.toml").open("rb") as f:
        excluded = tomllib.load(f)["tool"]["ruff"]["extend-exclude"]
    generated = [entry for entry in excluded if "engine_v1" in entry]
    assert generated == ["workers-py/common/src/ostia_common/engine_v1/engine_pb2.py*"]
