"""Requirements registry: generate requirements.yaml from the specification and the plan, and check it.

Usage:
  registry.py generate [--spec docs/spec.md] [--plan docs/plan.md] [--out requirements.yaml]
  registry.py validate [--registry requirements.yaml] [--schema schemas/requirements.schema.json]
  registry.py check    [--spec ...] [--plan ...] [--registry ...] [--schema ...]

Requirements are the rows of the specification tables whose first column is a requirement id. Rows
without a Phase column (the NFR table) take their phases from the work packages that cite them.
Parsing fails closed: a duplicate id, an id cited by the plan but absent from the specification, or an
unknown level, phase or ANSSI function stops the generation and nothing is written.
"""

import argparse
import json
import re
import sys
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import jsonschema
import yaml

REPO = Path(__file__).resolve().parents[2]
PREFIXES = ("FR", "NFR", "ENG", "USB", "DEEP", "ENR", "SEC", "CTR", "LOG", "UI", "UPD")
_FAMILY = "|".join(PREFIXES)
REQ_ID = re.compile(rf"\b(?:{_FAMILY})-\d{{2}}\b")
REQ_RANGE = re.compile(rf"\b({_FAMILY})-(\d{{2}}) to (?:\1-)?(\d{{2}})\b")
WP_ROW = re.compile(r"^WP-(\d+)\.(\d+)$")
PHASE = re.compile(r"^P(\d)$")
PHASE_RANGE = re.compile(r"^P(\d)\s*[–-]\s*P(\d)$")
ANSSI = re.compile(r"^FS([1-9]|1[0-5])$")
LEVELS = ("MUST", "SHOULD", "MAY")
NO_VALUE = ("—", "-")
POST_1_0 = "post-1.0"
HEADER = (
    "# Generated by tools/traceability/registry.py from docs/spec.md and docs/plan.md.\n"
    "# Do not edit: run `just registry`. Schema: schemas/requirements.schema.json\n"
)
TOOLING = {
    "id": "TOOLING",
    "level": "n/a",
    "phases": [],
    "phase_source": "reserved",
    "anssi": [],
    "section": "reserved",
    "text": "Tests of helpers, fixtures and tooling that prove no product requirement",
}


class RegistryError(Exception):
    """The sources or the registry do not allow a correct registry."""


@dataclass
class Row:
    """One requirement row of the specification."""

    rid: str
    section: str
    columns: dict[str, str]


def cells(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def spec_rows(spec: str) -> Iterator[Row]:
    section = ""
    header: list[str] = []
    for line in spec.splitlines():
        if line.startswith("## "):
            section = line[3:].strip()
            header = []
        if not line.startswith("|"):
            continue
        row = cells(line)
        if row[0] == "ID":
            header = row
            continue
        if header and REQ_ID.fullmatch(row[0]):
            if len(row) != len(header):
                raise RegistryError(f"{row[0]}: expected {len(header)} cells, found {len(row)}")
            yield Row(row[0], section, dict(zip(header, row, strict=True)))


def phase_order(phase: str) -> tuple[int, str]:
    match = PHASE.match(phase)
    return (int(match.group(1)), "") if match else (99, phase)


def parse_phases(rid: str, cell: str) -> list[str]:
    if cell == "after 1.0":
        return [POST_1_0]
    match = PHASE_RANGE.match(cell)
    if match:
        first, last = int(match.group(1)), int(match.group(2))
        if first < last:
            return [f"P{n}" for n in range(first, last + 1)]
    phases = [part.strip() for part in cell.split(",")]
    if cell and all(PHASE.match(p) for p in phases):
        return sorted(set(phases), key=phase_order)
    raise RegistryError(f"{rid}: unknown phase {cell!r}")


def parse_anssi(rid: str, cell: str) -> list[str]:
    if cell in NO_VALUE:
        return []
    functions = [part.strip() for part in cell.split(",")]
    for function in functions:
        if not ANSSI.match(function):
            raise RegistryError(f"{rid}: unknown ANSSI {function!r}")
    return functions


def expand_ids(text: str) -> list[str]:
    ids: list[str] = []
    for match in REQ_RANGE.finditer(text):
        family, first, last = match.group(1), int(match.group(2)), int(match.group(3))
        ids.extend(f"{family}-{n:02d}" for n in range(first, last + 1))
    ids.extend(REQ_ID.findall(text))
    return list(dict.fromkeys(ids))


def plan_citations(plan: str) -> dict[str, list[str]]:
    """Work package id -> requirement ids cited in its Requirements column."""
    citations: dict[str, list[str]] = {}
    for line in plan.splitlines():
        if not line.startswith("| WP-"):
            continue
        row = cells(line)
        if len(row) >= 3 and WP_ROW.match(row[0]):
            citations[row[0]] = expand_ids(row[2])
    return citations


def build(spec: str, plan: str) -> dict[str, Any]:
    """The registry document for these sources."""
    rows: dict[str, Row] = {}
    for row in spec_rows(spec):
        if row.rid in rows:
            raise RegistryError(f"duplicate requirement id {row.rid}")
        rows[row.rid] = row
    if not rows:
        raise RegistryError("no requirement rows found in the specification")

    cited_by: dict[str, set[str]] = {rid: set() for rid in rows}
    unknown = []
    for wid, ids in plan_citations(plan).items():
        phase = "P" + wid.removeprefix("WP-").split(".")[0]
        for rid in ids:
            if rid not in rows:
                unknown.append(f"{wid} cites {rid}, which is not in the spec")
            else:
                cited_by[rid].add(phase)
    if unknown:
        raise RegistryError("; ".join(unknown))

    entries: list[dict[str, Any]] = []
    for rid, row in rows.items():
        columns = row.columns
        level = columns.get("Level", "")
        if level not in LEVELS:
            raise RegistryError(f"{rid}: unknown level {level!r}")
        text = columns.get("Requirement", "")
        if not text:
            raise RegistryError(f"{rid}: empty requirement text")
        if "Phase" in columns:
            phases, source = parse_phases(rid, columns["Phase"]), "spec"
        else:
            phases = sorted(cited_by[rid], key=phase_order)
            source = "plan" if phases else "none"
        entry: dict[str, Any] = {
            "id": rid,
            "level": level,
            "phases": phases,
            "phase_source": source,
            "anssi": parse_anssi(rid, columns.get("ANSSI", "—")),
            "section": row.section,
        }
        if "Area" in columns:
            entry["area"] = columns["Area"]
        entry["text"] = text
        entries.append(entry)
    entries.append(dict(TOOLING))
    return {"version": 1, "requirements": entries}


def render(document: dict[str, Any]) -> str:
    body = yaml.safe_dump(document, sort_keys=False, allow_unicode=True, width=100)
    return HEADER + body


def validate(document: object, schema: dict[str, Any]) -> int:
    """Number of entries of a schema-valid registry with unique ids."""
    try:
        jsonschema.validate(document, schema, cls=jsonschema.Draft202012Validator)
    except jsonschema.ValidationError as exc:
        location = "/".join(str(part) for part in exc.absolute_path)
        raise RegistryError(f"{location or 'document'}: {exc.message}") from exc
    except jsonschema.SchemaError as exc:
        raise RegistryError(f"the schema itself is invalid: {exc.message}") from exc
    if not isinstance(document, dict):
        raise RegistryError("document: not a mapping")
    seen: set[str] = set()
    for entry in document["requirements"]:
        if entry["id"] in seen:
            raise RegistryError(f"duplicate id {entry['id']}")
        seen.add(entry["id"])
    return len(seen)


def load_registry(path: Path) -> object:
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        raise RegistryError(f"cannot read {path}: {exc}") from exc


def load_schema(path: Path) -> dict[str, Any]:
    try:
        schema: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise RegistryError(f"cannot read schema {path}: {exc}") from exc
    return schema


def read_sources(args: argparse.Namespace) -> tuple[str, str]:
    try:
        return args.spec.read_text(encoding="utf-8"), args.plan.read_text(encoding="utf-8")
    except OSError as exc:
        raise RegistryError(str(exc)) from exc


def cmd_generate(args: argparse.Namespace) -> int:
    text = render(build(*read_sources(args)))
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


def cmd_validate(args: argparse.Namespace) -> int:
    try:
        count = validate(load_registry(args.registry), load_schema(args.schema))
    except RegistryError as exc:
        print(f"registry invalid: {exc}", file=sys.stderr)
        return 1
    print(f"registry valid: {count} entries")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    expected = render(build(*read_sources(args)))
    try:
        count = validate(load_registry(args.registry), load_schema(args.schema))
    except RegistryError as exc:
        print(f"registry invalid: {exc}", file=sys.stderr)
        return 1
    if args.registry.read_text(encoding="utf-8") != expected:
        print(f"{args.registry.name} is out of date: run `just registry`", file=sys.stderr)
        return 1
    print(f"registry up to date: {count} entries")
    return 0


def parser() -> argparse.ArgumentParser:
    main_parser = argparse.ArgumentParser(description="Ostia requirements registry")
    commands = main_parser.add_subparsers(dest="command", required=True)
    sources = argparse.ArgumentParser(add_help=False)
    sources.add_argument("--spec", type=Path, default=REPO / "docs" / "spec.md")
    sources.add_argument("--plan", type=Path, default=REPO / "docs" / "plan.md")
    registry = argparse.ArgumentParser(add_help=False)
    registry.add_argument("--registry", type=Path, default=REPO / "requirements.yaml")
    registry.add_argument(
        "--schema", type=Path, default=REPO / "schemas" / "requirements.schema.json"
    )
    generate = commands.add_parser("generate", parents=[sources])
    generate.add_argument("--out", type=Path, default=REPO / "requirements.yaml")
    generate.set_defaults(run=cmd_generate)
    commands.add_parser("validate", parents=[registry]).set_defaults(run=cmd_validate)
    commands.add_parser("check", parents=[sources, registry]).set_defaults(run=cmd_check)
    return main_parser


def main(argv: list[str]) -> int:
    args = parser().parse_args(argv)
    try:
        code: int = args.run(args)
    except RegistryError as exc:
        print(f"registry: {exc}", file=sys.stderr)
        return 1
    return code


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
